ord/urls.py
from django.urls import path
from .views import *




urlpatterns = [
    path(r'', contactform, name='order'),
    path(r'thanks/', thanks, name='thanks'),
    # path(r'', DeskListView.as_view(), name='order'),
	
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('main.urls')),
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls'), name='blog'),
	path('gallery/', include('gallery.urls'), name='gallery'),
    path('order/', include('ord.urls'), name='order'),
    path('information/', include('information.urls'), name='information'),
    path('contakty/', include('contakty.urls'), name='contakty'),
    path('oferta/', include('prod.urls'), name='oferta'),
    path( "ckeditor5 /" ,  include ( 'django_ckeditor_5.urls' )),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ord/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Description(models.Model):
	"""Description for form order"""
	title = models.CharField(max_length=30)
	text = CKEditor5Field('Текст статьи')

	def __str__(self):
		return self.title



ord/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

ord/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm
from django.urls import reverse
from .models import Description
from django.views.generic import ListView


def contactform(reguest): 
    
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']         
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recepients = ['khatskevychmaksym@ukr.net']
            # Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recepients.append(sender)
            try:
                send_mail(subject, message, 'khatskevychmaksym@ukr.net', recepients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            # Переходим на другую страницу, если сообщение отправлено
            return HttpResponseRedirect(reverse('thanks'))

    else:
        form = ContactForm()
        template_name = Description.objects.all()
        context = {
                   'form': form, 
                   'template_name': template_name 
                    }
    # Выводим форму в шаблон
    return render(reguest, 'ord/order.html', context)
        

def thanks(reguest):
    thanks = 'thanks'
    return render(reguest, 'ord/thanks.html', {'thanks': thanks})    


    """'username': auth.get_user(reguest).username"""

"""class DeskListView(ListView):
    
    def get(self,request):
        template_name = Description.objects.all()
        return render(request, 'ord/order.html', {'template_name': template_name} )"""



  

templates/ord/order.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% load static %}

{% block title %}
    Orders
{% endblock %}

{% block content %}
 
<div>
<div class="example-class">

    <div class="card border-primary mb-3" style="max-width: 18rem;">
      {% for template_name in template_name %}
        <div class="card-header">{{ template_name.title }}</div>
            <div class="card-body text-primary">
                <p class="card-text">{{ template_name.text|safe }}</p>   
            </div>
        </div>
    {% endfor %}
    </div>
</div>
<div class="panel-success">
    <div class="panel-heading">
        <h2 class="panel-title">Обратная связь</h2>
    </div>
        <div class="panel-body">
            <div class="well well-lg">
                <form action="{% url 'order' %}" method="post">
                    {% csrf_token %}
                    {#    {% bootstrap_form form %}#}
                    {{ form.non_field_errors }}
                    <div>
                        <div>
                            <label for="id_subject">Imię i nazwisko:</label>
                            {{ form.subject.errors }}
                            {#    {{ form.subject }}#}
                            <input class="form-control" id="id_subject" name="subject" placeholder="Imię i nazwisko">
                        </div>
                        &nbsp;
                        <div>
                            <label for="id_sender">E-mail:</label>
                            {{ form.sender.errors }}
                            {#    {{ form.sender }}#}
                            <input class="form-control" id="id_sender" name="sender" placeholder="e-mail">
                        </div>
                        &nbsp;
                        <div>
                            <label for="id_message">Wiadomość:</label>
                            {{ form.message.errors }}
                            {#    {{ form.message }}#}
                            <textarea class="form-control" id="id_message" name="message"
                                      placeholder="Potszeba wpisać szczegóły zamówienia "></textarea>
                        </div>
                        &nbsp;
                        <div>
                            {{ form.copy.errors }}
                            <label for="id_copy">{{ form.copy }} Wysłać copię </label>
                        </div>
                        <br>
                        <input type="submit" class="btn btn-success" align="center" value="Wysłać"/>
                </form>
            </div>
        </div>
</div>
</div>    

{% endblock %}





 


















templates/ord/thanks.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% load static %}

{% block content %}

    <div class="panel panel-success">
        <div class="panel-heading">
            <h2 class="panel-title"></h2>
        </div>
        <div class="panel-body">
            <div class="well well-lg" align="center">
                <h3>Спасибо, Ваше сообщение отправлено!</h3>
                <div align="center"><a href="/">
                    <button type="button" class="btn btn-info">Вернутся на главную</button>
                </a></div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}