blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.inblog, name='blog-inblog'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

ord/urls.py
from django.urls import path
from .views import *




urlpatterns = [
    path(r'', contactform, name='order'),
    path(r'thanks/', thanks, name='thanks'),
    # path(r'', DeskListView.as_view(), name='order'),
	
    
]

prod/urls.py
from django.urls import path
from . import views

app_name = 'oferta'

urlpatterns = [
    path('', views.inblog, name='blog-inblog'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('main.urls')),
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls'), name='blog'),
	path('gallery/', include('gallery.urls'), name='gallery'),
    path('order/', include('ord.urls'), name='order'),
    path('information/', include('information.urls'), name='information'),
    path('contakty/', include('contakty.urls'), name='contakty'),
    path('oferta/', include('prod.urls'), name='oferta'),
    path( "ckeditor5 /" ,  include ( 'django_ckeditor_5.urls' )),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/oferta/oferta.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Oferta
{% endblock %}

{% block content %}

    <table class="photo-block" style="border: none">
        {% for a in latest_articles_list %}
            {% if forloop.counter0|divisibleby:3 %}
                <tr class="gallery-tr">
            {% endif %}
        <td class="blog-img">

            <a class="img-flu images" href="{{ a.image.url }}">
                <img class="img-flu" src="{{ a.image.url }}">
                <div class="blog-body">
                    <h5 class="blog-title">"{{ a.title }}"</h5>

                    <a href="{% url 'oferta:detail' a.id %}" class="blog-btn">Read more</a>
                </div>
            </a>
        </td>
        {% if forloop.counter|divisibleby:3 %}
            </tr>
        {% endif %}
        {% endfor %}
        </tr>
    </table>
    <div class="lightbox">
        <div class="lightbox-cnt">
            <img src="" class="lightbox-img" alt="">
            <button class="lightbox-close"><span>&#10006;</span></button>
        </div>
    </div>
    </div>

    </div>
{% endblock %}


templates/oferta/oferta_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    <div class='blog'>
        <div class="oferta-img"><img src="{{ article.image.url }}"></div>
        <h1 class='blog-title'>"{{ article.title|safe }}"</h1>
        <p class='blog-text'>{% autoescape off %}{{ article.text|safe }}{% endautoescape %}</p>
        <em>{{ article.pub_date }}</em>
    </div>

   <!-- {% if article.was_published_recently %}
        <div class="alert alert-danger" role="alert">
            <h2>NEW ARTICLE!</h2>
        </div>
    {% endif %}

    <hr>
    {% if latest_comments_list %}
        {% for c in latest_comments_list %}
            <p>
                <strong>{{ c.author_name }}</strong>
            <p>{{ c.comment_text }}</p>
            <em>{{ c.pub_date }}</em>
            </p>
        {% endfor %}
    {% else %}
        <h3>No comments found! Be the first!</h3>
    {% endif %}
    <hr>
    {% if message %}
        <h3 style="color: red" align="center">{{ message }}</h3>
    {% endif %}
    <form action='{% url "blog:leave_comment" article.id %}' method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="formGroupExampleInput">Your name</label>
            <input type="text" class="form-control" id="formGroupExampleInput" name='name'>
        </div>
        <div class="form-group">
            <label for="exampleInputComment">Your comment</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name='text'></textarea><br>
            <button type="submite" class="btn btn-outline-primary">Leave the comment</button>
    </form>
    </div>
    </form>
    </div>
{% endblock %}